export const PLATFORM = "MV_CORE_PLATFORM";
export const SCOPED_CONTAINER = "MV_CORE_SCOPED_CONTAINER";
export const SCOPED_RESOLVER = "MV_CORE_SCOPED_RESOLVER";
export const LOGGING_PROVIDER = "MV_LOGGING_PROVIDER";
export const LOGGING_FORMATTER = "MV_LOGGING_FORMATTER";
export const LOGGING_FILTER = "MV_LOGGING_FILTER";
export const LOGGER_NAMESPACE = "MV_LOGGER_NAMESPACE";
export const LOGGER_NAME = "MV_LOGGER_NAME";
